/**
    Copyright 2014-2015 Amazon.com, Inc. or its affiliates. All Rights Reserved.

    Licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at

        http://aws.amazon.com/apache2.0/

    or in the "license" file accompanying this file. This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
*/

module.exports = {
    "chicken breast":"boneless, skinless chicken breast, should be grilled 8 to 12 minutes over direct medium heat.",
    "chicken thighs":"boneless, skinless chicken thighs, should be grilled 8 to 10 minutes over direct medium heat.",
    "steak":"a three quarter inch thick steak, should be grilled for 4 to 6 minutes over direct high heat.  A one inch thick steak, should be grilled 6 to 8 minutes over direct high heat.  A two inch thick steak should be grilled 14 to 18 minutes, with 6 to 8 minutes over direct high heat, and then 8 to 10 minutes over indirect high heat.",
    "new york strip":"a three quarter inch thick new your strip, should be grilled for 4 to 6 minutes over direct high heat.  A one inch thick new your strip, should be grilled 6 to 8 minutes over direct high heat.  A two inch thick new your strip should be grilled 14 to 18 minutes, with 6 to 8 minutes over direct high heat, and then 8 to 10 minutes over indirect high heat.",
    "porterhouse":"a three quarter inch thick porterhouse, should be grilled for 4 to 6 minutes over direct high heat.  A one inch thick porterhouse, should be grilled 6 to 8 minutes over direct high heat.  A two inch thick porterhouse should be grilled 14 to 18 minutes, with 6 to 8 minutes over direct high heat, and then 8 to 10 minutes over indirect high heat.",
    "rib-eye":"a three quarter inch thick rib-eye, should be grilled for 4 to 6 minutes over direct high heat.  A one inch thick rib-eye, should be grilled 6 to 8 minutes over direct high heat.  A two inch thick rib-eye should be grilled 14 to 18 minutes, with 6 to 8 minutes over direct high heat, and then 8 to 10 minutes over indirect high heat.",
    "t-bone":"a three quarter inch thick t-bone, should be grilled for 4 to 6 minutes over direct high heat.  A one inch thick t-bone, should be grilled 6 to 8 minutes over direct high heat.  A two inch thick t-bone should be grilled 14 to 18 minutes, with 6 to 8 minutes over direct high heat, and then 8 to 10 minutes over indirect high heat.",
    "filet mignon":"a three quarter inch thick filet mignon, should be grilled for 4 to 6 minutes over direct high heat.  A one inch thick filet mignon, should be grilled 6 to 8 minutes over direct high heat.  A two inch thick filet mignon should be grilled 14 to 18 minutes, with 6 to 8 minutes over direct high heat, and then 8 to 10 minutes over indirect high heat.",
    "beef tenerloin":"a beef tenderloin of 3 to 4 pounds, should be grilled for 45 to 60 minutes over indirect high heat.",
    "flank steak":"a flank steak of 1 and a half to 2 pounds, and three quarters of an inch thick should be grilled for 8 to 10 minutes over direct medium heat",
    "ground beef patty":"a hamburger that is three quarters of an inch thick, should be grilled for 8 to 10 minutes, over direct medium heat",
    "hamburger":"a hamburger that is three quarters of an inch thick, should be grilled for 8 to 10 minutes, over direct medium heat",
    "burger":"a hamburger that is three quarters of an inch thick, should be grilled for 8 to 10 minutes, over direct medium heat",
    "bratwurst":"a bratwurst should be grilled for 20 to 25 minutes over direct low heat",
    "brat":"a bratwurst should be grilled for 20 to 25 minutes over direct low heat",
    "italian sausage":"an italian sausage should be grilled for 20 to 25 minutes over direct low heat",
    "polish sausage":"a polish sausage should be grilled for 20 to 25 minutes over direct low heat",
    "pork chop":"a three quarter inch thick pork chop, should be grilled for 4 to 6 minutes over direct high heat.  A one and a quarter to one and a half inch thick pork chop, should be grilled 10 to 12 minutes, searing for 6 minutes over direct high heat, and grilled 4 to 6 minutes over indirect high heat",
    "boneless pork chop":"a three quarter inch thick pork chop, should be grilled for 4 to 6 minutes over direct high heat.  A one and a quarter to one and a half inch thick pork chop, should be grilled 10 to 12 minutes, searing for 6 minutes over direct high heat, and grilled 4 to 6 minutes over indirect high heat",
    "bone in pork chop":"a three quarter inch thick pork chop, should be grilled for 4 to 6 minutes over direct high heat.  A one and a quarter to one and a half inch thick pork chop, should be grilled 10 to 12 minutes, searing for 6 minutes over direct high heat, and grilled 4 to 6 minutes over indirect high heat",
    "baby back ribs":"baby back ribs should be grilled for one and a half to two hours over indirect medium heat",
    "spareribs":"baby back ribs should be grilled for one and a half to two hours over indirect medium heat",
    "country style ribs":"baby back ribs should be grilled for one and a half to two hours over indirect medium heat",
    "pork tenerloin":"a pork tenderloin of 1 pound, should be grilled for 30 minutes, seared for 5 minutes over direct high heat followed by 25 minutes over indirect medium heat.",
    "chicken pieces":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "bone in chicken pieces":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "bone in chicken":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "bone in chicken thighs":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "bone in chicken breasts":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "bone in chicken legs":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "chicken drum stick":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "bone in chicken wings":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "chicken wings":"bone in chicken pieces should be grilled for 36 to 40 minutes, with 6 to 10 minutes over direct low heat, then 30 minutes over indirect medium heat",
    "whole chicken":"a whole chicken should be grilled for 1 to 1 and a quarter hours over indirect medium heat",
    "cornish game hen":"a cornish game hen should be grilled 60 to 70 minutes over indirect medium heat",
    "turkey":"a whole turkey of 10 to 12 pounds should be grilled 2 to 2 and a half hours over indirect medium heat",
    "whole turkey":"a whole turkey of 10 to 12 pounds should be grilled 2 to 2 and a half hours over indirect medium heat",
    "fish":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "fish fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "fish steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "halibut":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "halibut fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "halibut steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "red snapper":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "red snapper fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "red snapper steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "salmon":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "salmon fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "salmon steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "sea bass":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "sea bass fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "sea bass steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "swordfish":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "swordfish fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "swordfish steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "tuna":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "tuna fillet":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "tuna steak":"a quarter inch to half inch thick piece of fish, should be grilled for 3 to 5 minutes over direct medium heat.  A one to one and a quarter inch thick piece of fish, should be grilled 10 to 12 minutes, over direct medium heat",
    "shrimp":"shrimp should be grilled 2 to 4 minutes over direct high heat",
    "asparagus":"asparagus should be grilled 6 to 8 minutes over direct medium heat",
    "corn":"corn in the husk should be grilled 25 to 30 minutes overdirect medium heat.  Corn that has been husked should be grilled 10 to 15 minutes over direct medium heat",
    "mushrooms":"shiitake or button mushrooms should be grilled 8 to 10 minutes over direct medium heat.  Portabello mushrooms should be grilled 10 to 15 minutes over direct medium heat",
    "onion":"Onions that are halved should be grilled 35 to 40 minutes over indirect medium heat.  Half inch slices of onions should be grilled 8 to 12 minutes over direct medium heat",
    "potato":"whole potatoes should be grilled 45 to 60 minutes over indirect medium heat.  Half inch slices should be cooked 9 to 11 minutes, first parboiling for 3 minutes, and then grilled 6 to 8 minutes over direct medium heat"
    
};
